# ============================================================
# TaskGraph-Edge CNN Accelerator Constraints
# Board: Xilinx ZC706 Evaluation Board (Zynq-7000, XC7Z045)
# ============================================================
#
# IMPORTANT: The PS FCLK_CLK0 clock is generated by the
# processing_system7 IP. Do NOT re-define it here or it
# will conflict with the auto-generated constraint.
#

# ============================================================
# Status LEDs
# ============================================================
# LED[0] = Processing (busy)
# LED[1] = Done
# LED[2] = Data In
# LED[3] = Data Out

# GPIO_LED_0 (LVCMOS15, Bank 35)
set_property PACKAGE_PIN A17 [get_ports {status_leds[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {status_leds[0]}]

# GPIO_LED_CENTER (LVCMOS15, Bank 33)
set_property PACKAGE_PIN G2 [get_ports {status_leds[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {status_leds[1]}]

# GPIO_LED_RIGHT (LVCMOS25)
set_property PACKAGE_PIN W21 [get_ports {status_leds[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {status_leds[2]}]

# GPIO_LED_LEFT (LVCMOS25)
set_property PACKAGE_PIN Y21 [get_ports {status_leds[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {status_leds[3]}]

# ============================================================
# Streaming Data Ports — mapped to PMOD1 header
# ============================================================
# These are the external streaming ports from the block design.
# Mapped to PMOD1 pins (LVCMOS25, active on ZC706).

# stream_data_in_0[7:0] — PMOD1 pins 0-7
set_property PACKAGE_PIN AJ21 [get_ports {stream_data_in_0[0]}]
set_property PACKAGE_PIN AK21 [get_ports {stream_data_in_0[1]}]
set_property PACKAGE_PIN AB21 [get_ports {stream_data_in_0[2]}]
set_property PACKAGE_PIN AB16 [get_ports {stream_data_in_0[3]}]
set_property PACKAGE_PIN Y20  [get_ports {stream_data_in_0[4]}]
set_property PACKAGE_PIN AA20 [get_ports {stream_data_in_0[5]}]
set_property PACKAGE_PIN AC18 [get_ports {stream_data_in_0[6]}]
set_property PACKAGE_PIN AC19 [get_ports {stream_data_in_0[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {stream_data_in_0[*]}]

# stream_data_out_0[7:0] — FMC_LPC_LA00 through LA03 (P/N pairs)
set_property PACKAGE_PIN AE13 [get_ports {stream_data_out_0[0]}]
set_property PACKAGE_PIN AF13 [get_ports {stream_data_out_0[1]}]
set_property PACKAGE_PIN AF15 [get_ports {stream_data_out_0[2]}]
set_property PACKAGE_PIN AG15 [get_ports {stream_data_out_0[3]}]
set_property PACKAGE_PIN AE12 [get_ports {stream_data_out_0[4]}]
set_property PACKAGE_PIN AF12 [get_ports {stream_data_out_0[5]}]
set_property PACKAGE_PIN AG12 [get_ports {stream_data_out_0[6]}]
set_property PACKAGE_PIN AH12 [get_ports {stream_data_out_0[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {stream_data_out_0[*]}]

# Handshaking signals — FMC_LPC_LA04, LA05
set_property PACKAGE_PIN AJ15 [get_ports stream_in_valid_0]
set_property IOSTANDARD LVCMOS25 [get_ports stream_in_valid_0]

set_property PACKAGE_PIN AK15 [get_ports stream_in_ready_0]
set_property IOSTANDARD LVCMOS25 [get_ports stream_in_ready_0]

set_property PACKAGE_PIN AE16 [get_ports stream_out_valid_0]
set_property IOSTANDARD LVCMOS25 [get_ports stream_out_valid_0]

set_property PACKAGE_PIN AE15 [get_ports stream_out_ready_0]
set_property IOSTANDARD LVCMOS25 [get_ports stream_out_ready_0]

# ============================================================
# Optimization & DRC
# ============================================================
set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]

# Bitstream settings
set_property BITSTREAM.CONFIG.UNUSEDPIN Pulldown [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
